import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.scene.Node;

/**
 * This class handles button presses in the statistics panel.
 *
 * @author Ayesha Dorani (K2036136)
 * @version 30.03.2022
 */
public class StatisticsEventHandler implements EventHandler<Event> {

    /**
     * Processes the events generated by the user when a button has been clicked.
     *
     * @param event The event that has occurred.
     */
    @Override
    public void handle(Event event) {
        Node node = (Node) event.getSource(); // gets the source of the event
        Statistics.changeStats(node);
    }
}
